Repository kaltura/playkit-js-ima, pull requests merged in 2018-03, with the labels that each got.

#46 feat: ad type
  src/ad-type.js
  src/ima-state-machine.js
  test/src/ima.api.spec.js
  test/src/ima.spec.js
Labels: Priority: High, Type: Feature

#47 fix(FEC-8065): protect against accessing IMA SDK when it is not loaded
  src/ima.js
Labels: Priority: High, Type: Bug

#49 feat(FEC-7814): add setAdWillAutoPlay and setAdWillPlayMuted support
  src/ima.js
Labels: Priority: Medium, Type: Feature
