Repository kaltura/playkit-js-ima, pull requests merged in 2019-10, with the labels that each got.

#137 fix(FEC-9313): IOS when configuration autoplay native weird behaviour
  src/ima.js
Labels: Type: Bug

#138 fix(FEC-9373): new layout, the player stuck if skip pre-roll ad
  src/ima.js
Labels: Priority: High, Type: Bug

#141 fix(FEC-9290): destroy adDisplayContainer on destroy
  src/ima.js
Labels: Type: Bug

#142 fix(FEC-9429): new ad layout - stopped source will autoplay if AD_ERROR occurs on preroll URL
  src/ima.js
Labels: Priority: High, Type: Bug

#139 feat(FEC-9293): ad waterfalling
  src/ima-state-machine.js
  src/ima.js
Labels: Priority: High, Type: Feature
