Repository kaltura/playkit-js-ima, pull requests merged in 2019-08, with the labels that each got.

#127 fix(FEC-9273): playing preroll on AV player (ios+playsinline=false) gets the player stuck
  src/ima-state-machine.js
  src/ima.js
Labels: Priority: High, Type: Bug

#130 fix: non relevant code after engine decorator
  src/ima-state-machine.js
  src/ima.js
Labels: Type: Maintenance

#129 fix(FEC-9160): captions displayed during midroll ad on AVplayer
  src/ima-state-machine.js
  src/ima.js
Labels: Type: Bug

#131 fix: broken mp4 in tests
  samples/companion-ads-automatic.html
  samples/companion-ads-manual.html
  samples/play-ad-now.html
  samples/single-inline-linear.html
  samples/single-non-linear-inline.html
  samples/single-redirect-broken(fallback).html
  samples/single-redirect-error.html
  samples/single-redirect-linear.html
  samples/single-skippable-inline.html
  samples/single-vpaid-2.0-linear.html
  samples/vmap-bumpers-pre-1-mid-3-post-1.html
  samples/vmap-post-bumper.html
  samples/vmap-post.html
  samples/vmap-pre-1-mid-1-post-1.html
  samples/vmap-pre-1-mid-5-post-1.html
  samples/vmap-pre-bumper.html
  samples/vmap-pre-skip-support.html
  samples/vmap-pre.html
  src/index.html
  test/src/helpers.js
Labels: Type: Bug

#132 fix(FEC-9160): disable tacks on mid-roll
  src/ima.js
Labels: Type: Bug

#133 fix(FEC-9160): track keep showing in background and other keeps playing
  src/ima-state-machine.js
  src/ima.js
Labels: Type: Bug
