Repository kaltura/playkit-js-ima, pull requests merged in 2019-07, with the labels that each got.

#121 feat(FEC-9145): support non sibling video tags
  package.json
  src/ima-engine-decorator.js
  src/ima-state-machine.js
  src/ima.js
  yarn.lock
Labels: Priority: High, Type: Feature

#125 feat(FEC-9158): preload chain
  src/ima-middleware.js
Labels: Priority: High

#123 feat(FEC-9227): support reInit of MSE
  docs/api.md
  flow-typed/types/ima-config.js
  src/ima-engine-decorator.js
  src/ima-state-machine.js
  src/ima.js
Labels: Type: Feature

#126 fix(FEC-9237): add app protocol for ima plugin
  package.json
  src/ima.js
  yarn.lock
Labels: Type: Bug
