Repository kaltura/playkit-js-ima, pull requests merged in 2019-06, with the labels that each got.

#114 fix(FEC-9111): seekbar doesn't work on WebOS
  src/ima.js
Labels: Type: Bug

#113 fix(FEC-9173): playback failed for unsupported ads.
  src/ima-engine-decorator.js
  src/ima-state-machine.js
  src/ima.js
Labels: Type: Bug

#115 fix(FEC-9167): set default IMA lib protocol for non http protocols
  src/ima.js
Labels: Type: Bug

#96 feat(FEC-8631): bumper plugin
  karma.conf.js
  package.json
  src/ima-ads-controller.js
  src/ima-state-machine.js
  src/ima.js
  test/src/ima.spec.js
  yarn.lock
Labels: Priority: High, Type: Feature

#117 fix(FEC-9192): post bumper doesn't play
  src/ima-ads-controller.js
Labels: Priority: High, Type: Bug

#116 fix(FEC-9173): playback failed for unsupported ads.
  src/ima-engine-decorator.js
  src/ima-state-machine.js
  src/ima.js
Labels: Type: Bug

#119 fix(FEC-9209): when bumper and ima plugins enabled in player, no big replay button at the end
  src/ima.js
Labels: Priority: High, Type: Bug
