Repository kaltura/playkit-js-ima, pull requests merged in 2019-01, with the labels that each got.

#85 feat(FEC-8749): expose IMA ad data
  package.json
  src/ima-state-machine.js
  test/src/ima.spec.js
  yarn.lock
Labels: Priority: High, Type: Feature

#87 feat(FEC-8751): add support for ima playAdsAfterTime setting
  src/ima.js
  test/src/ima.spec.js
Labels: Priority: High, Type: Feature

#88 feat(FEC-8763): add loadMedia life cycle hook
  package.json
  src/ima.js
  yarn.lock
Labels: Type: Feature

#89 feat(FEC-8815): support vast timeout
  src/ima.js
Labels: Priority: Medium

#90 feat(FEC-8853): localizing ima interface via config
  docs/api.md
  flow-typed/types/ima-config.js
  src/ima.js
Labels: Priority: Medium, Type: Feature

#92 chore: add locale to jsdocs
  flow-typed/types/ima-config.js
Labels: Priority: Medium
